version: '3.9'

services:
  hello_world:
    container_name: hello_world
    hostname: hello_world
    build:
      context: ./code
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./code:/code
